apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-janitor
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-janitor-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-janitor-binding
subjects:
  - kind: ServiceAccount
    name: kube-janitor
    namespace: default
roleRef:
  kind: ClusterRole
  name: kube-janitor-role
  apiGroup: rbac.authorization.k8s.io
